import rules.C_A3 as C_A3
import rules.C_C1 as C_C1
import rules.C_C2 as C_C2
import rules.C_C3 as C_C3
import rules.C_F2 as C_F2
import rules.C_F3 as C_F3
import rules.C_F4 as C_F4
import rules.C_F5 as C_F5
import rules.C_F6 as C_F6
import rules.C_F7 as C_F7
import rules.C_F8 as C_F8
import rules.C_F9 as C_F9
import rules.C_G1 as C_G1
import rules.C_G2 as C_G2
import rules.C_G3 as C_G3
import rules.C_G4 as C_G4
import rules.C_G5 as C_G5
import rules.C_G6 as C_G6
import rules.C_G7 as C_G7
import rules.C_G8 as C_G8
import rules.C_H1 as C_H1
import rules.C_H2 as C_H2
import rules.C_L1 as C_L1
import rules.C_L2 as C_L2
import rules.C_L3 as C_L3
import rules.C_L4 as C_L4
import rules.C_L5 as C_L5
import rules.C_L6 as C_L6
import rules.C_O1 as C_O1
import rules.C_O3 as C_O3
import rules.C_O4 as C_O4
import rules.C_V1 as C_V1
import rules.C_FN as C_FN